[project]
name = "sisso"
version = "2024.0.0"
requires-python = ">=3.10"
authors = [{ name = "Arsen Hnatiuk", email = "arsen.hnatiuk@hu-berlin.de" }]
readme = "README.md"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
